'use strict';

const user = {
  account: 'Account',
  username: 'Username',
  org: 'Orgnization',
  phone: 'Phone No.',
  workNo: 'Work No.',
  password: 'Password',
};
const role = {
  roleCode: 'Role Code',
  roleName: 'Role Name',
  warehouse: 'Warehouse',
};
const userGroup = {
  userGroupCode: 'User Group Code',
  userGroupName: 'User Group Name',
};
const edit = {
  submit: 'Next',
  submitAndreturn: 'Save',
  return: 'Return',
};
const list = {
  createdAt: 'Created Date',
  updatedAt: 'Last Modified Date',
  createdUser: 'Created User',
  updatedUser: 'Last Modified User',
  new: 'New',
  lock: 'Lock',
  unlock: 'Unlock',
  del: 'Delete',
  op: 'Operation',
  'op.edit': 'Edit',
  popConfirm: 'Confirm to delete?',
  popOk: 'Confirm',
  popCancel: 'Cancel',
  lockScs: 'Lock Operation Succeed!',
  unlockScs: 'Unlock Operation Succeed!',
  delScs: 'Delete Operation Succeed!',
};
module.exports = {
  'menu.system': 'System Management',
  'menu.returnMainSystem': 'Return Upstream System',
  userManagement: {
    menu: 'User Authority Management',
    'menu.userList': 'User',
    'menu.roleList': 'Role',
    'menu.userGroupList': 'User Group',
    'menu.userEdit': 'User Edit',
    'menu.userGroupEdit': 'User Group Edit',
    'menu.roleEdit': 'Role Edit',
    'menu.permissionEdit': 'Permission Edit',
    'lockState.unlocked': 'Unlocked',
    'lockState.locked': 'Locked',
    status: 'Status',
    outDateAt: 'Expiring Date',
    'commitType.missing': 'Commit type is missing, please go back to list page!',
    moveDirectionError: 'Change direction Error!',
    list,
    edit,
    user,
    userList: {
      title: 'User',
      'op.role': 'Show Roles',
      roleView: 'Roles',
      'op.userGroup': 'Show User Groups',
      userGroupView: 'User Groups',
      'op.permission': 'Show Permissions',
      delConfirm: 'Please confirm delete {:selectedRows.length} users?',
    },
    userEdit: {
      setRole: 'Add Roles',
      passwordMin: 'Password must not be less than 6 bits',
      passwordMax: 'Password must not be more than 20 bits',
      'submit.new.scs': 'Create new user succeed!',
      'submit.edit.scs': 'Modify user info succeed!',
      updateRoleScs: 'Update user roles succeed!',
    },
    role,
    roleList: {
      title: 'Role',
      'op.permission': 'Set Permissions',
      delConfirm: 'Please confirm delete {:selectedRows.length} roles?',
    },
    roleEdit: {
      addUser: 'Add User',
      roleUpdateUserScs: 'Update role users succeed!',
      roleUpdateUserFail: 'Update role users failed!',
      roleUpdateUserGroupScs: 'Update role user groups succeed!',
      roleUpdateUserGroupFail: 'Update role user groups failed!',
    },
    userGroup,
    userGroupList: {
      title: 'User Group',
      warehouse: 'Warehouse',
      'op.user': 'Show Users',
      userView: 'User',
      'op.role': 'Show Roles',
      roleView: 'Roles',
      'op.permission': 'Show Permissions',
      delConfirm: 'Please confirm delete {:selectedRows.length} user groups?',
    },
    userGroupEdit: {
      addUser: 'Add User',
      'submit.new.scs': 'Create new user group succeed!',
      'submit.edit.scs': 'Modify user group info succeed!',
      updateUserScs: 'Update user group users succeed!',
    },
    permissionEdit: {
      updateScs: 'Update permissions succeed!',
    },
  },
};
